language: node_js
node_js:
  - "node"
os: osx

notifications:
  webhooks:
    urls:
      - https://travis-ci.org/
  email:
    recipients:
      - jshanthi19@gmail.com

env:
  matrix:
    - TEST_COMMAND="npm run test"

script: ${TEST_COMMAND}
